### ISSUE TITLE
HTTP Error 500.50 - URL Rewrite Module Error

### ISSUE THREAD

**Issue by alandillon** [shibayan/IIS.Compression.SiteExtension#9]
This issue happens after the extension is installed and the site is restarted.

Another person having the issue:  https://social.msdn.microsoft.com/Forums/en-US/d2a8fc5b-26b8-416f-9fee-861217118871/enable-brotli-compression-in-app-service-web-app?forum=windowsazurewebsitespreview 

![image](https://user-images.githubusercontent.com/3331097/57866697-c3e3d480-77cd-11e9-9c2c-26f295234a5f.png)

**Comment by a9261** [comment]
I have same issue. after install this extension

**Comment by shibayan** [comment]
This problem has been fixed in v1.1.1. Thank you for the report.

**Comment by nixa333** [comment]
@shibayan   I just installed v1.1.1 but still have the same problem
![image](https://user-images.githubusercontent.com/6515226/58477733-92b3be80-8154-11e9-8e43-9a1cbbcef76e.png)

Could be that I'm using ASP.NET core?

**Comment by shibayan** [comment]
More information is required because it is not reproduced in my environment.
Do you have any site extensions installed?

**Comment by nixa333** [comment]
These three 

![image](https://user-images.githubusercontent.com/6515226/58478301-030f0f80-8156-11e9-8763-34a740aaff9a.png)

**Comment by kyurthich** [comment]
Also still have the issue:

![image](https://user-images.githubusercontent.com/3331097/58479077-7e0c0200-8125-11e9-8f94-0b9ce66f5e38.png)


![image](https://user-images.githubusercontent.com/3331097/58479203-c4616100-8125-11e9-9e97-aa5d1630e7e6.png)

**### Environment variables**
ALLUSERSPROFILE = D:\local\ProgramData
APP_POOL_CONFIG = C:\DWASFiles\Sites\#1xx\Config\applicationhost.config
APP_POOL_ID = ~1xx
APPDATA = D:\local\AppData
APPINSIGHTS_INSTRUMENTATIONKEY = ccc106d9-bcb8-436d-ba3e-fcdc61891fca
APPINSIGHTS_PROFILERFEATURE_VERSION = 1.0.0
APPINSIGHTS_SNAPSHOTFEATURE_VERSION = 1.0.0
ApplicationInsightsAgent_EXTENSION_VERSION = ~2
APPSETTING_APPINSIGHTS_INSTRUMENTATIONKEY = ccc106d9-bcb8-436d-ba3e-fcdc61891fca
APPSETTING_APPINSIGHTS_PROFILERFEATURE_VERSION = 1.0.0
APPSETTING_APPINSIGHTS_SNAPSHOTFEATURE_VERSION = 1.0.0
APPSETTING_ApplicationInsightsAgent_EXTENSION_VERSION = ~2
APPSETTING_DiagnosticServices_EXTENSION_VERSION = ~3
APPSETTING_InstrumentationEngine_EXTENSION_VERSION = ~1
APPSETTING_REMOTEDEBUGGINGVERSION = 15.0.28307.222
APPSETTING_ScmType = VSTSRM
APPSETTING_SnapshotDebugger_EXTENSION_VERSION = ~1
APPSETTING_WEBSITE_AUTH_AUTO_AAD = False
APPSETTING_WEBSITE_AUTH_ENABLED = False
APPSETTING_WEBSITE_AUTH_LOGOUT_PATH = /.auth/logout
APPSETTING_WEBSITE_RUN_FROM_PACKAGE = 0
APPSETTING_WEBSITE_SITE_NAME = xx
APPSETTING_XDT_MicrosoftApplicationInsights_BaseExtensions = ~1
APPSETTING_XDT_MicrosoftApplicationInsights_Mode = recommended
AZURE_JETTY9_CMDLINE = -Djava.net.preferIPv4Stack=true -Djetty.port=%HTTP_PLATFORM_PORT% -Djetty.base="D:\Program Files (x86)\jetty-distribution-9.1.0.v20131115" -Djetty.webapps="d:\home\site\wwwroot\webapps" -jar "D:\Program Files (x86)\jetty-distribution-9.1.0.v20131115\start.jar" etc\jetty-logging.xml
AZURE_JETTY9_HOME = D:\Program Files (x86)\jetty-distribution-9.1.0.v20131115
AZURE_JETTY93_CMDLINE = -Djava.net.preferIPv4Stack=true -Djetty.port=%HTTP_PLATFORM_PORT% -Djetty.base="D:\Program Files (x86)\jetty-distribution-9.3.25.v20180904" -Djetty.webapps="d:\home\site\wwwroot\webapps" -jar "D:\Program Files (x86)\jetty-distribution-9.3.25.v20180904\start.jar" etc\jetty-logging.xml
AZURE_JETTY93_HOME = D:\Program Files (x86)\jetty-distribution-9.3.25.v20180904
AZURE_TOMCAT7_CMDLINE = -Dport.http=%HTTP_PLATFORM_PORT% -Djava.util.logging.config.file="D:\Program Files (x86)\apache-tomcat-7.0.50\conf\logging.properties" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dsite.logdir="d:/home/LogFiles/" -Dsite.tempdir="d:\home\site\workdir" -classpath "D:\Program Files (x86)\apache-tomcat-7.0.50\bin\bootstrap.jar;D:\Program Files (x86)\apache-tomcat-7.0.50\bin\tomcat-juli.jar" -Dcatalina.base="D:\Program Files (x86)\apache-tomcat-7.0.50" -Djava.io.tmpdir="d:\home\site\workdir" org.apache.catalina.startup.Bootstrap
AZURE_TOMCAT7_HOME = D:\Program Files (x86)\apache-tomcat-7.0.50
AZURE_TOMCAT8_CMDLINE = -Dport.http=%HTTP_PLATFORM_PORT% -Djava.util.logging.config.file="D:\Program Files (x86)\apache-tomcat-8.0.23\conf\logging.properties" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dsite.logdir="d:/home/LogFiles/" -Dsite.tempdir="d:\home\site\workdir" -classpath "D:\Program Files (x86)\apache-tomcat-8.0.23\bin\bootstrap.jar;D:\Program Files (x86)\apache-tomcat-8.0.23\bin\tomcat-juli.jar" -Dcatalina.base="D:\Program Files (x86)\apache-tomcat-8.0.23" -Djava.io.tmpdir="d:\home\site\workdir" org.apache.catalina.startup.Bootstrap
AZURE_TOMCAT8_HOME = D:\Program Files (x86)\apache-tomcat-8.0.23
AZURE_TOMCAT85_CMDLINE = -noverify -Djava.net.preferIPv4Stack=true -Dcatalina.instance.name=%WEBSITE_INSTANCE_ID% -Dport.http=%HTTP_PLATFORM_PORT% -Djava.util.logging.config.file="D:\Program Files (x86)\apache-tomcat-8.5.37\conf\logging.properties" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dsite.logdir="d:/home/LogFiles/" -Dsite.tempdir="d:\home\site\workdir" -classpath "D:\Program Files (x86)\apache-tomcat-8.5.37\bin\bootstrap.jar;D:\Program Files (x86)\apache-tomcat-8.5.37\bin\tomcat-juli.jar" -Dcatalina.base="D:\Program Files (x86)\apache-tomcat-8.5.37" -Djava.io.tmpdir="d:\home\site\workdir" org.apache.catalina.startup.Bootstrap
AZURE_TOMCAT85_HOME = D:\Program Files (x86)\apache-tomcat-8.5.37
AZURE_TOMCAT90_CMDLINE = -noverify -Djava.net.preferIPv4Stack=true -Dcatalina.instance.name=%WEBSITE_INSTANCE_ID% -Dport.http=%HTTP_PLATFORM_PORT% -Djava.util.logging.config.file="D:\Program Files (x86)\apache-tomcat-9.0.14\conf\logging.properties" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dsite.logdir="d:/home/LogFiles/" -Dsite.tempdir="d:\home\site\workdir" -classpath "D:\Program Files (x86)\apache-tomcat-9.0.14\bin\bootstrap.jar;D:\Program Files (x86)\apache-tomcat-9.0.14\bin\tomcat-juli.jar" -Dcatalina.base="D:\Program Files (x86)\apache-tomcat-9.0.14" -Djava.io.tmpdir="d:\home\site\workdir" org.apache.catalina.startup.Bootstrap
AZURE_TOMCAT90_HOME = D:\Program Files (x86)\apache-tomcat-9.0.14
CommonProgramFiles = D:\Program Files (x86)\Common Files
CommonProgramFiles(x86) = D:\Program Files (x86)\Common Files
CommonProgramW6432 = D:\Program Files\Common Files
COMPUTERNAME = RD00155D4BDF5F
ComSpec = D:\Windows\system32\cmd.exe
DIAGNOSTIC_SERVICES_EXTENSION_BASE_PATH = D:\Program Files (x86)\SiteExtensions\DiagnosticServices\3.4.1904
DiagnosticServices_EXTENSION_VERSION = ~3
DOTNET_CLI_TELEMETRY_PROFILE = AzureKudu
DOTNET_HOSTING_OPTIMIZATION_CACHE = D:\DotNetCache
DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
HOME = D:\home
HOME_EXPANDED = C:\DWASFiles\Sites\#1xx\VirtualDirectory0
HTTP_HOST = xx.scm.azurewebsites.net
InstrumentationEngine_EXTENSION_VERSION = ~1
JAVA_HOME = D:\Program Files\Java\zulu8.31.0.2-jre8.0.181-win_x64
LOCAL_EXPANDED = C:\DWASFiles\Sites\#1xx
LOCALAPPDATA = D:\local\LocalAppData
NUGET_PACKAGES = D:\home\.nuget\
NUGET_XMLDOC_MODE = skip
NUMBER_OF_PROCESSORS = 2
OS = Windows_NT
Path = D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\81.10329.3844\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files\Git\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files (x86)\nodejs\0.10.28;D:\Program Files (x86)\npm\1.4.28;C:\DWASFiles\Sites\#1xx\AppData\npm;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\funcpack\1.0.0;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\81.10329.3844\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files\Git\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files (x86)\nodejs\0.10.28;D:\Program Files (x86)\npm\1.4.28;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\funcpack\1.0.0;D:\Program Files (x86)\nodejs;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;D:\Program Files (x86)\dotnet;D:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\PHP\v5.6;D:\Python27;
PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW
PROCESSOR_ARCHITECTURE = x86
PROCESSOR_ARCHITEW6432 = AMD64
PROCESSOR_IDENTIFIER = Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
PROCESSOR_LEVEL = 6
PROCESSOR_REVISION = 3f02
ProgramData = D:\local\ProgramData
ProgramFiles = D:\Program Files (x86)
ProgramFiles(x86) = D:\Program Files (x86)
ProgramW6432 = D:\Program Files
PSModulePath = D:\Program Files\WindowsPowerShell\Modules;D:\Windows\system32\WindowsPowerShell\v1.0\Modules;D:\Program Files\WindowsPowerShell\Modules\;D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\;D:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage\;D:\Program Files\Microsoft Message Analyzer\PowerShell\
PUBLIC = D:\Users\Public
REGION_NAME = South Central US
REMOTEDEBUGGINGBITVERSION = vx86
REMOTEDEBUGGINGPORT =
REMOTEDEBUGGINGVERSION = 15.0.28307.222
SCM_SKIP_SSL_VALIDATION = 0
ScmType = VSTSRM
SITE_BITNESS = x86
SnapshotDebugger_EXTENSION_VERSION = ~1
SQLAZURECONNSTR_SurgereConnection = Server=tcp:xx.database.windows.net;Database=xx-main;User ID={user};Password={pword};Trusted_Connection=False;Encrypt=True;
SQLAZURECONNSTR_SurgereRFIDConnection = Server=tcp:hmcsqlscuqa01.database.windows.net;Database=hmcsqlscuqa01-main;User ID={user};Password={pword};Trusted_Connection=False;Encrypt=True;
SystemDrive = D:
SystemRoot = D:\Windows
TEMP = D:\local\Temp
TMP = D:\local\Temp
USERDOMAIN = WORKGROUP
USERNAME = RD00155D4BDF5F$
USERPROFILE = D:\local\UserProfile
WEBSITE_AUTH_AUTO_AAD = False
WEBSITE_AUTH_ENABLED = False
WEBSITE_AUTH_ENCRYPTION_KEY = BA9DB9E661B289945DFAF413626104050951443A07836EED42D7CFAB91593D7E
WEBSITE_AUTH_LOGOUT_PATH = /.auth/logout
WEBSITE_AUTH_SIGNING_KEY = 9F4BC2CEF02953F5FE4A7C443D0279A1425B891E2A3539B23906D22EBC22E313
WEBSITE_COMPUTE_MODE = Dedicated
WEBSITE_CONFIGURATION_READY = 1
WEBSITE_CONTAINER_READY = 1
WEBSITE_CURRENT_STAMPNAME = waws-prod-sn1-103g
WEBSITE_DYNAMIC_CACHE = 1
WEBSITE_ELASTIC_SCALING_ENABLED = 0
WEBSITE_FRAMEWORK_JIT = 1
WEBSITE_HOME_STAMPNAME = waws-prod-sn1-103
WEBSITE_HOSTNAME = xx.azurewebsites.net
WEBSITE_HTTPLOGGING_ENABLED = 0
WEBSITE_IIS_SITE_NAME = ~1xx
WEBSITE_INSTANCE_ID = 88f3cddbfc5f5d5e21808695089a4099f774af143eaf7481ed3e836dcceaa201
WEBSITE_LOCALCACHE_ENABLED = False
WEBSITE_OWNER_NAME = e7ac75cf-3685-44f7-b24f-c45a81d2cb67+sur-qa-rg-SouthCentralUSwebspace
WEBSITE_RELAYS =
WEBSITE_RESOURCE_GROUP = sur-qa-rg
WEBSITE_REWRITE_TABLE =
WEBSITE_RUN_FROM_PACKAGE = 0
WEBSITE_SCM_ALWAYS_ON_ENABLED = 1
WEBSITE_SCM_SEPARATE_STATUS = 1
WEBSITE_SITE_NAME = xx
WEBSITE_SKU = PremiumV2
WEBSITE_VOLUME_TYPE = PrimaryStorageVolume
WEBSOCKET_CONCURRENT_REQUEST_LIMIT = -1
windir = D:\Windows
windows_tracing_flags =
windows_tracing_logfile =
XDT_MicrosoftApplicationInsights_BaseExtensions = ~1
XDT_MicrosoftApplicationInsights_Mode = recommended
XENON = 0

**### HTTP headers**
Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding=gzip, deflate, br
Accept-Language=en-US,en;q=0.9
CLIENT-IP=98.102.6.82:57598
Connection=Keep-Alive
Cookie=ai_user=VV5ga|2019-05-08T20:53:14.970Z; ARRAffinity=88f3cddbfc5f5d5e21808695089a4099f774af143eaf7481ed3e836dcceaa201
DISGUISED-HOST=xx.scm.azurewebsites.net
Host=xx.scm.azurewebsites.net
Max-Forwards=10
Referer=https://xx.scm.azurewebsites.net/
Sec-Fetch-Mode=navigate
Sec-Fetch-Site=same-origin
Sec-Fetch-User=?1
Upgrade-Insecure-Requests=1
User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3789.0 Safari/537.36 Edg/76.0.159.0
WAS-DEFAULT-HOSTNAME=xx.scm.azurewebsites.net
X-ARR-LOG-ID=2751c194-a71b-400a-bc37-3a5687b8bd91
X-ARR-SSL=2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 4|CN=*.azurewebsites.net
X-Forwarded-For=98.102.6.82:57598
X-Forwarded-Proto=https
X-MS-CLIENT-DISPLAY-NAME=Client Name
X-MS-CLIENT-PRINCIPAL-NAME=email@place.com
X-Original-URL=/Env.cshtml
X-SITE-DEPLOYMENT-ID=xx
X-WAWS-Unencoded-URL=/Env.cshtml


**### Server variables**
ALL_HTTP=HTTP_CONNECTION:Keep-Alive HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3 HTTP_ACCEPT_ENCODING:gzip, deflate, br HTTP_ACCEPT_LANGUAGE:en-US,en;q=0.9 HTTP_COOKIE:ai_user=VV5ga|2019-05-08T20:53:14.970Z; ARRAffinity=88f3cddbfc5f5d5e21808695089a4099f774af143eaf7481ed3e836dcceaa201 HTTP_HOST:xx.scm.azurewebsites.net HTTP_MAX_FORWARDS:10 HTTP_REFERER:https://xx.scm.azurewebsites.net/ HTTP_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3789.0 Safari/537.36 Edg/76.0.159.0 HTTP_UPGRADE_INSECURE_REQUESTS:1 HTTP_SEC_FETCH_MODE:navigate HTTP_SEC_FETCH_SITE:same-origin HTTP_SEC_FETCH_USER:?1 HTTP_X_WAWS_UNENCODED_URL:/Env.cshtml HTTP_CLIENT_IP:98.102.6.82:57598 HTTP_X_ARR_LOG_ID:2751c194-a71b-400a-bc37-3a5687b8bd91 HTTP_DISGUISED_HOST:xx.scm.azurewebsites.net HTTP_X_SITE_DEPLOYMENT_ID:xx HTTP_WAS_DEFAULT_HOSTNAME:xx.scm.azurewebsites.net HTTP_X_ORIGINAL_URL:/Env.cshtml HTTP_X_MS_CLIENT_PRINCIPAL_NAME:email@place.com HTTP_X_MS_CLIENT_DISPLAY_NAME:client name HTTP_X_FORWARDED_FOR:98.102.6.82:57598 HTTP_X_ARR_SSL:2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 4|CN=*.azurewebsites.net HTTP_X_FORWARDED_PROTO:https
ALL_RAW=Connection: Keep-Alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3 Accept-Encoding: gzip, deflate, br Accept-Language: en-US,en;q=0.9 Cookie: ai_user=VV5ga|2019-05-08T20:53:14.970Z; ARRAffinity=88f3cddbfc5f5d5e21808695089a4099f774af143eaf7481ed3e836dcceaa201 Host: xx.scm.azurewebsites.net Max-Forwards: 10 Referer: https://xx.scm.azurewebsites.net/ User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3789.0 Safari/537.36 Edg/76.0.159.0 Upgrade-Insecure-Requests: 1 Sec-Fetch-Mode: navigate Sec-Fetch-Site: same-origin Sec-Fetch-User: ?1 X-WAWS-Unencoded-URL: /Env.cshtml CLIENT-IP: 98.102.6.82:57598 X-ARR-LOG-ID: 2751c194-a71b-400a-bc37-3a5687b8bd91 DISGUISED-HOST: xx.scm.azurewebsites.net X-SITE-DEPLOYMENT-ID: xx WAS-DEFAULT-HOSTNAME: xx.scm.azurewebsites.net X-Original-URL: /Env.cshtml X-MS-CLIENT-PRINCIPAL-NAME: email@place.com X-MS-CLIENT-DISPLAY-NAME: client name X-Forwarded-For: 98.102.6.82:57598 X-ARR-SSL: 2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 4|CN=*.azurewebsites.net X-Forwarded-Proto: https
APPL_MD_PATH=/LM/W3SVC/1954020088/ROOT
APPL_PHYSICAL_PATH=D:\Program Files (x86)\SiteExtensions\Kudu\81.10329.3844\
AUTH_PASSWORD=
AUTH_TYPE=
AUTH_USER=
CERT_COOKIE=
CERT_FLAGS=
CERT_ISSUER=
CERT_KEYSIZE=256
CERT_SECRETKEYSIZE=2048
CERT_SERIALNUMBER=
CERT_SERVER_ISSUER=C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 4
CERT_SERVER_SUBJECT=CN=*.azurewebsites.net
CERT_SUBJECT=
CONTENT_LENGTH=0
CONTENT_TYPE=
GATEWAY_INTERFACE=CGI/1.1
HTTP_ACCEPT=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
HTTP_ACCEPT_ENCODING=gzip, deflate, br
HTTP_ACCEPT_LANGUAGE=en-US,en;q=0.9
HTTP_CLIENT_IP=98.102.6.82:57598
HTTP_CONNECTION=Keep-Alive
HTTP_COOKIE=ai_user=VV5ga|2019-05-08T20:53:14.970Z; ARRAffinity=88f3cddbfc5f5d5e21808695089a4099f774af143eaf7481ed3e836dcceaa201
HTTP_DISGUISED_HOST=xx.scm.azurewebsites.net
HTTP_HOST=xx.scm.azurewebsites.net
HTTP_MAX_FORWARDS=10
HTTP_REFERER=https://xx.scm.azurewebsites.net/
HTTP_SEC_FETCH_MODE=navigate
HTTP_SEC_FETCH_SITE=same-origin
HTTP_SEC_FETCH_USER=?1
HTTP_UPGRADE_INSECURE_REQUESTS=1
HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3789.0 Safari/537.36 Edg/76.0.159.0
HTTP_WAS_DEFAULT_HOSTNAME=xx.scm.azurewebsites.net
HTTP_X_ARR_LOG_ID=2751c194-a71b-400a-bc37-3a5687b8bd91
HTTP_X_ARR_SSL=2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 4|CN=*.azurewebsites.net
HTTP_X_FORWARDED_FOR=98.102.6.82:57598
HTTP_X_FORWARDED_PROTO=https
HTTP_X_MS_CLIENT_DISPLAY_NAME=client name
HTTP_X_MS_CLIENT_PRINCIPAL_NAME=email@place.com
HTTP_X_ORIGINAL_URL=/Env.cshtml
HTTP_X_SITE_DEPLOYMENT_ID=xx
HTTP_X_WAWS_UNENCODED_URL=/Env.cshtml
HTTPS=on
HTTPS_KEYSIZE=256
HTTPS_SECRETKEYSIZE=2048
HTTPS_SERVER_ISSUER=C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 4
HTTPS_SERVER_SUBJECT=CN=*.azurewebsites.net
INSTANCE_ID=1954020088
INSTANCE_META_PATH=/LM/W3SVC/1954020088
LOCAL_ADDR=10.0.6.181
LOGON_USER=
PATH_INFO=/Env.cshtml
PATH_TRANSLATED=D:\Program Files (x86)\SiteExtensions\Kudu\81.10329.3844\Env.cshtml
QUERY_STRING=
REMOTE_ADDR=98.102.6.82
REMOTE_HOST=98.102.6.82
REMOTE_PORT=57598
REMOTE_USER=
REQUEST_METHOD=GET
SCRIPT_NAME=/Env.cshtml
SERVER_NAME=xx.scm.azurewebsites.net
SERVER_PORT=443
SERVER_PORT_SECURE=1
SERVER_PROTOCOL=HTTP/1.1
SERVER_SOFTWARE=Microsoft-IIS/10.0
URL=/Env.cshtml

**Comment by shibayan** [comment]
It seems to be a compatibility issue with the App Insights Site Extension.
The App Insights Site Extension version 2.6.5 is not already maintained and should be uninstalled. It is recommended to enable App Insights from Azure Portal instead.

![image](https://user-images.githubusercontent.com/1356444/58479852-04f7c380-8194-11e9-8b93-5d589c297b9c.png)

**Comment by alandillon** [comment]
I had the issue without that extension installed. 

I have it enabled there and in my app as well via nuget.

**Comment by shibayan** [comment]
I will release an update to mitigate this issue. It will probably be v1.1.2.

**Comment by alandillon** [comment]
![image](https://user-images.githubusercontent.com/3331097/58480166-be6c7f80-8127-11e9-850f-171e88b83a84.png)


![image](https://user-images.githubusercontent.com/3331097/58480208-d8a65d80-8127-11e9-939f-56e0fc322a5b.png)

**Comment by alandillon** [comment]
Ok Sounds good

**Comment by shibayan** [comment]
I released it so try it.
https://www.nuget.org/packages/IIS.Compression.SiteExtension/1.1.2

**Comment by alandillon** [comment]
Fixed! Thank you very much.
